INSERT INTO products (product_name, department_name, price, stock)
VALUES ("camping tarp", "camping", "325.00", "8")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("headlamp", "camping", "25.99", "50")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("road bike", "sporting", "999.99", "5")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("mountain bike", "sporting", "1499.99", "9")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("trail shoes", "running", "120.00", "12")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("hydration vest", "running", "134.00", "4")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("titanium cookset", "camping", "120.00", "3")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("running watch", "running", "250.00", "10")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("wool balaclava", "skiing", "30.00", "7")
INSERT INTO products (product_name, department_name, price, stock)
VALUES ("wool baselayer", "skiing", "99.99", "4");
